// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source file empty.proto

import Foundation
import ProtocolBuffers


internal extension Google.Protobuf{}

internal func == (lhs: Google.Protobuf.Empty, rhs: Google.Protobuf.Empty) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal extension Google.Protobuf {
  internal struct EmptyRoot {
    internal static var sharedInstance : EmptyRoot {
     struct Static {
         static let instance : EmptyRoot = EmptyRoot()
     }
     return Static.instance
    }
    internal var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    internal func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final internal class Empty : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.Empty {
      return Google.Protobuf.Empty.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.EmptyRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Empty {
      return Google.Protobuf.Empty.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.Empty {
      return Google.Protobuf.Empty.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Empty {
      return Google.Protobuf.Empty.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Empty {
      return Google.Protobuf.Empty.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Empty {
      return Google.Protobuf.Empty.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.EmptyBuilder {
      return Google.Protobuf.Empty.classBuilder() as! Google.Protobuf.EmptyBuilder
    }
    internal func builder() -> Google.Protobuf.EmptyBuilder {
      return classBuilder() as! Google.Protobuf.EmptyBuilder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.EmptyBuilder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Empty.builder()
    }
    internal func toBuilder() -> Google.Protobuf.EmptyBuilder {
      return Google.Protobuf.Empty.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.Empty) -> Google.Protobuf.EmptyBuilder {
      return Google.Protobuf.Empty.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.Empty"
    }
    override internal func className() -> String {
        return "Google.Protobuf.Empty"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.Empty.self
    }
    //Meta information declaration end

  }

  final internal class EmptyBuilder : GeneratedMessageBuilder {
    private var builderResult:Google.Protobuf.Empty = Google.Protobuf.Empty()

    required override internal init () {
       super.init()
    }
    override internal var internalGetResult:GeneratedMessage {
         get {
            return builderResult
         }
    }
    internal override func clear() -> Google.Protobuf.EmptyBuilder {
      builderResult = Google.Protobuf.Empty()
      return self
    }
    internal override func clone() -> Google.Protobuf.EmptyBuilder {
      return Google.Protobuf.Empty.builderWithPrototype(builderResult)
    }
    internal override func build() -> Google.Protobuf.Empty {
         checkInitialized()
         return buildPartial()
    }
    internal func buildPartial() -> Google.Protobuf.Empty {
      var returnMe:Google.Protobuf.Empty = builderResult
      return returnMe
    }
    internal func mergeFrom(other:Google.Protobuf.Empty) -> Google.Protobuf.EmptyBuilder {
      if other == Google.Protobuf.Empty() {
       return self
      }
      mergeUnknownFields(other.unknownFields)
      return self
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.EmptyBuilder {
         return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
    }
    internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.EmptyBuilder {
      var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
      while (true) {
        var tag = input.readTag()
        switch tag {
        case 0: 
          self.unknownFields = unknownFieldsBuilder.build()
          return self

        default:
          if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
             unknownFields = unknownFieldsBuilder.build()
             return self
          }
        }
      }
    }
  }

}

// @@protoc_insertion_point(global_scope)
