// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source file wrappers.proto

import Foundation
import ProtocolBuffers


internal extension Google.Protobuf{}

internal func == (lhs: Google.Protobuf.DoubleValue, rhs: Google.Protobuf.DoubleValue) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.FloatValue, rhs: Google.Protobuf.FloatValue) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.Int64Value, rhs: Google.Protobuf.Int64Value) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.Uint64Value, rhs: Google.Protobuf.Uint64Value) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.Int32Value, rhs: Google.Protobuf.Int32Value) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.Uint32Value, rhs: Google.Protobuf.Uint32Value) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.BoolValue, rhs: Google.Protobuf.BoolValue) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.StringValue, rhs: Google.Protobuf.StringValue) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal func == (lhs: Google.Protobuf.BytesValue, rhs: Google.Protobuf.BytesValue) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasValue == rhs.hasValue) && (!lhs.hasValue || lhs.value == rhs.value)
  return (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
}

internal extension Google.Protobuf {
  internal struct WrappersRoot {
    internal static var sharedInstance : WrappersRoot {
     struct Static {
         static let instance : WrappersRoot = WrappersRoot()
     }
     return Static.instance
    }
    internal var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    internal func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final internal class DoubleValue : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:Double = Double(0)

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeDouble(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeDoubleSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.DoubleValue {
      return Google.Protobuf.DoubleValue.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.DoubleValue {
      return Google.Protobuf.DoubleValue.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.DoubleValue {
      return Google.Protobuf.DoubleValue.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.DoubleValue {
      return Google.Protobuf.DoubleValue.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.DoubleValue {
      return Google.Protobuf.DoubleValue.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.DoubleValue {
      return Google.Protobuf.DoubleValue.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.DoubleValue.Builder {
      return Google.Protobuf.DoubleValue.classBuilder() as! Google.Protobuf.DoubleValue.Builder
    }
    internal func builder() -> Google.Protobuf.DoubleValue.Builder {
      return classBuilder() as! Google.Protobuf.DoubleValue.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.DoubleValue.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.DoubleValue.builder()
    }
    internal func toBuilder() -> Google.Protobuf.DoubleValue.Builder {
      return Google.Protobuf.DoubleValue.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.DoubleValue) -> Google.Protobuf.DoubleValue.Builder {
      return Google.Protobuf.DoubleValue.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.DoubleValue"
    }
    override internal func className() -> String {
        return "Google.Protobuf.DoubleValue"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.DoubleValue.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.DoubleValue = Google.Protobuf.DoubleValue()
      internal func getMessage() -> Google.Protobuf.DoubleValue {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:Double {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:Double) -> Google.Protobuf.DoubleValue.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.DoubleValue.Builder{
           builderResult.hasValue = false
           builderResult.value = Double(0)
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.DoubleValue.Builder {
        builderResult = Google.Protobuf.DoubleValue()
        return self
      }
      internal override func clone() -> Google.Protobuf.DoubleValue.Builder {
        return Google.Protobuf.DoubleValue.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.DoubleValue {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.DoubleValue {
        var returnMe:Google.Protobuf.DoubleValue = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.DoubleValue) -> Google.Protobuf.DoubleValue.Builder {
        if other == Google.Protobuf.DoubleValue() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.DoubleValue.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.DoubleValue.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 9 :
            value = input.readDouble()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class FloatValue : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:Float = Float(0)

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeFloat(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeFloatSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.FloatValue {
      return Google.Protobuf.FloatValue.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.FloatValue {
      return Google.Protobuf.FloatValue.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.FloatValue {
      return Google.Protobuf.FloatValue.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.FloatValue {
      return Google.Protobuf.FloatValue.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.FloatValue {
      return Google.Protobuf.FloatValue.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.FloatValue {
      return Google.Protobuf.FloatValue.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.FloatValue.Builder {
      return Google.Protobuf.FloatValue.classBuilder() as! Google.Protobuf.FloatValue.Builder
    }
    internal func builder() -> Google.Protobuf.FloatValue.Builder {
      return classBuilder() as! Google.Protobuf.FloatValue.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.FloatValue.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.FloatValue.builder()
    }
    internal func toBuilder() -> Google.Protobuf.FloatValue.Builder {
      return Google.Protobuf.FloatValue.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.FloatValue) -> Google.Protobuf.FloatValue.Builder {
      return Google.Protobuf.FloatValue.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.FloatValue"
    }
    override internal func className() -> String {
        return "Google.Protobuf.FloatValue"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.FloatValue.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.FloatValue = Google.Protobuf.FloatValue()
      internal func getMessage() -> Google.Protobuf.FloatValue {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:Float {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:Float) -> Google.Protobuf.FloatValue.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.FloatValue.Builder{
           builderResult.hasValue = false
           builderResult.value = Float(0)
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.FloatValue.Builder {
        builderResult = Google.Protobuf.FloatValue()
        return self
      }
      internal override func clone() -> Google.Protobuf.FloatValue.Builder {
        return Google.Protobuf.FloatValue.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.FloatValue {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.FloatValue {
        var returnMe:Google.Protobuf.FloatValue = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.FloatValue) -> Google.Protobuf.FloatValue.Builder {
        if other == Google.Protobuf.FloatValue() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.FloatValue.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.FloatValue.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 13 :
            value = input.readFloat()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class Int64Value : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:Int64 = Int64(0)

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeInt64(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeInt64Size(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.Int64Value {
      return Google.Protobuf.Int64Value.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int64Value {
      return Google.Protobuf.Int64Value.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.Int64Value {
      return Google.Protobuf.Int64Value.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int64Value {
      return Google.Protobuf.Int64Value.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Int64Value {
      return Google.Protobuf.Int64Value.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int64Value {
      return Google.Protobuf.Int64Value.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.Int64Value.Builder {
      return Google.Protobuf.Int64Value.classBuilder() as! Google.Protobuf.Int64Value.Builder
    }
    internal func builder() -> Google.Protobuf.Int64Value.Builder {
      return classBuilder() as! Google.Protobuf.Int64Value.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Int64Value.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Int64Value.builder()
    }
    internal func toBuilder() -> Google.Protobuf.Int64Value.Builder {
      return Google.Protobuf.Int64Value.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.Int64Value) -> Google.Protobuf.Int64Value.Builder {
      return Google.Protobuf.Int64Value.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.Int64Value"
    }
    override internal func className() -> String {
        return "Google.Protobuf.Int64Value"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.Int64Value.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.Int64Value = Google.Protobuf.Int64Value()
      internal func getMessage() -> Google.Protobuf.Int64Value {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:Int64 {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:Int64) -> Google.Protobuf.Int64Value.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.Int64Value.Builder{
           builderResult.hasValue = false
           builderResult.value = Int64(0)
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.Int64Value.Builder {
        builderResult = Google.Protobuf.Int64Value()
        return self
      }
      internal override func clone() -> Google.Protobuf.Int64Value.Builder {
        return Google.Protobuf.Int64Value.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.Int64Value {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.Int64Value {
        var returnMe:Google.Protobuf.Int64Value = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.Int64Value) -> Google.Protobuf.Int64Value.Builder {
        if other == Google.Protobuf.Int64Value() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Int64Value.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int64Value.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 8 :
            value = input.readInt64()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class Uint64Value : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:UInt64 = UInt64(0)

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeUInt64(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeUInt64Size(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.Uint64Value {
      return Google.Protobuf.Uint64Value.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint64Value {
      return Google.Protobuf.Uint64Value.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.Uint64Value {
      return Google.Protobuf.Uint64Value.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint64Value {
      return Google.Protobuf.Uint64Value.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Uint64Value {
      return Google.Protobuf.Uint64Value.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint64Value {
      return Google.Protobuf.Uint64Value.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.Uint64Value.Builder {
      return Google.Protobuf.Uint64Value.classBuilder() as! Google.Protobuf.Uint64Value.Builder
    }
    internal func builder() -> Google.Protobuf.Uint64Value.Builder {
      return classBuilder() as! Google.Protobuf.Uint64Value.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Uint64Value.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Uint64Value.builder()
    }
    internal func toBuilder() -> Google.Protobuf.Uint64Value.Builder {
      return Google.Protobuf.Uint64Value.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.Uint64Value) -> Google.Protobuf.Uint64Value.Builder {
      return Google.Protobuf.Uint64Value.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.Uint64Value"
    }
    override internal func className() -> String {
        return "Google.Protobuf.Uint64Value"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.Uint64Value.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.Uint64Value = Google.Protobuf.Uint64Value()
      internal func getMessage() -> Google.Protobuf.Uint64Value {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:UInt64 {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:UInt64) -> Google.Protobuf.Uint64Value.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.Uint64Value.Builder{
           builderResult.hasValue = false
           builderResult.value = UInt64(0)
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.Uint64Value.Builder {
        builderResult = Google.Protobuf.Uint64Value()
        return self
      }
      internal override func clone() -> Google.Protobuf.Uint64Value.Builder {
        return Google.Protobuf.Uint64Value.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.Uint64Value {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.Uint64Value {
        var returnMe:Google.Protobuf.Uint64Value = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.Uint64Value) -> Google.Protobuf.Uint64Value.Builder {
        if other == Google.Protobuf.Uint64Value() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Uint64Value.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint64Value.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 8 :
            value = input.readUInt64()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class Int32Value : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:Int32 = Int32(0)

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeInt32(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeInt32Size(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.Int32Value {
      return Google.Protobuf.Int32Value.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int32Value {
      return Google.Protobuf.Int32Value.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.Int32Value {
      return Google.Protobuf.Int32Value.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int32Value {
      return Google.Protobuf.Int32Value.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Int32Value {
      return Google.Protobuf.Int32Value.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int32Value {
      return Google.Protobuf.Int32Value.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.Int32Value.Builder {
      return Google.Protobuf.Int32Value.classBuilder() as! Google.Protobuf.Int32Value.Builder
    }
    internal func builder() -> Google.Protobuf.Int32Value.Builder {
      return classBuilder() as! Google.Protobuf.Int32Value.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Int32Value.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Int32Value.builder()
    }
    internal func toBuilder() -> Google.Protobuf.Int32Value.Builder {
      return Google.Protobuf.Int32Value.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.Int32Value) -> Google.Protobuf.Int32Value.Builder {
      return Google.Protobuf.Int32Value.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.Int32Value"
    }
    override internal func className() -> String {
        return "Google.Protobuf.Int32Value"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.Int32Value.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.Int32Value = Google.Protobuf.Int32Value()
      internal func getMessage() -> Google.Protobuf.Int32Value {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:Int32 {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:Int32) -> Google.Protobuf.Int32Value.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.Int32Value.Builder{
           builderResult.hasValue = false
           builderResult.value = Int32(0)
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.Int32Value.Builder {
        builderResult = Google.Protobuf.Int32Value()
        return self
      }
      internal override func clone() -> Google.Protobuf.Int32Value.Builder {
        return Google.Protobuf.Int32Value.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.Int32Value {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.Int32Value {
        var returnMe:Google.Protobuf.Int32Value = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.Int32Value) -> Google.Protobuf.Int32Value.Builder {
        if other == Google.Protobuf.Int32Value() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Int32Value.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Int32Value.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 8 :
            value = input.readInt32()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class Uint32Value : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:UInt32 = UInt32(0)

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeUInt32(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeUInt32Size(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.Uint32Value {
      return Google.Protobuf.Uint32Value.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint32Value {
      return Google.Protobuf.Uint32Value.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.Uint32Value {
      return Google.Protobuf.Uint32Value.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint32Value {
      return Google.Protobuf.Uint32Value.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Uint32Value {
      return Google.Protobuf.Uint32Value.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint32Value {
      return Google.Protobuf.Uint32Value.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.Uint32Value.Builder {
      return Google.Protobuf.Uint32Value.classBuilder() as! Google.Protobuf.Uint32Value.Builder
    }
    internal func builder() -> Google.Protobuf.Uint32Value.Builder {
      return classBuilder() as! Google.Protobuf.Uint32Value.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Uint32Value.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.Uint32Value.builder()
    }
    internal func toBuilder() -> Google.Protobuf.Uint32Value.Builder {
      return Google.Protobuf.Uint32Value.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.Uint32Value) -> Google.Protobuf.Uint32Value.Builder {
      return Google.Protobuf.Uint32Value.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.Uint32Value"
    }
    override internal func className() -> String {
        return "Google.Protobuf.Uint32Value"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.Uint32Value.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.Uint32Value = Google.Protobuf.Uint32Value()
      internal func getMessage() -> Google.Protobuf.Uint32Value {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:UInt32 {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:UInt32) -> Google.Protobuf.Uint32Value.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.Uint32Value.Builder{
           builderResult.hasValue = false
           builderResult.value = UInt32(0)
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.Uint32Value.Builder {
        builderResult = Google.Protobuf.Uint32Value()
        return self
      }
      internal override func clone() -> Google.Protobuf.Uint32Value.Builder {
        return Google.Protobuf.Uint32Value.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.Uint32Value {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.Uint32Value {
        var returnMe:Google.Protobuf.Uint32Value = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.Uint32Value) -> Google.Protobuf.Uint32Value.Builder {
        if other == Google.Protobuf.Uint32Value() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.Uint32Value.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.Uint32Value.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 8 :
            value = input.readUInt32()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class BoolValue : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:Bool = false

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeBool(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeBoolSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.BoolValue {
      return Google.Protobuf.BoolValue.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BoolValue {
      return Google.Protobuf.BoolValue.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.BoolValue {
      return Google.Protobuf.BoolValue.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BoolValue {
      return Google.Protobuf.BoolValue.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.BoolValue {
      return Google.Protobuf.BoolValue.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BoolValue {
      return Google.Protobuf.BoolValue.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.BoolValue.Builder {
      return Google.Protobuf.BoolValue.classBuilder() as! Google.Protobuf.BoolValue.Builder
    }
    internal func builder() -> Google.Protobuf.BoolValue.Builder {
      return classBuilder() as! Google.Protobuf.BoolValue.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.BoolValue.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.BoolValue.builder()
    }
    internal func toBuilder() -> Google.Protobuf.BoolValue.Builder {
      return Google.Protobuf.BoolValue.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.BoolValue) -> Google.Protobuf.BoolValue.Builder {
      return Google.Protobuf.BoolValue.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.BoolValue"
    }
    override internal func className() -> String {
        return "Google.Protobuf.BoolValue"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.BoolValue.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.BoolValue = Google.Protobuf.BoolValue()
      internal func getMessage() -> Google.Protobuf.BoolValue {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:Bool {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:Bool) -> Google.Protobuf.BoolValue.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.BoolValue.Builder{
           builderResult.hasValue = false
           builderResult.value = false
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.BoolValue.Builder {
        builderResult = Google.Protobuf.BoolValue()
        return self
      }
      internal override func clone() -> Google.Protobuf.BoolValue.Builder {
        return Google.Protobuf.BoolValue.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.BoolValue {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.BoolValue {
        var returnMe:Google.Protobuf.BoolValue = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.BoolValue) -> Google.Protobuf.BoolValue.Builder {
        if other == Google.Protobuf.BoolValue() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.BoolValue.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BoolValue.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 8 :
            value = input.readBool()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class StringValue : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:String = ""

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeString(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeStringSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.StringValue {
      return Google.Protobuf.StringValue.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.StringValue {
      return Google.Protobuf.StringValue.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.StringValue {
      return Google.Protobuf.StringValue.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.StringValue {
      return Google.Protobuf.StringValue.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.StringValue {
      return Google.Protobuf.StringValue.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.StringValue {
      return Google.Protobuf.StringValue.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.StringValue.Builder {
      return Google.Protobuf.StringValue.classBuilder() as! Google.Protobuf.StringValue.Builder
    }
    internal func builder() -> Google.Protobuf.StringValue.Builder {
      return classBuilder() as! Google.Protobuf.StringValue.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.StringValue.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.StringValue.builder()
    }
    internal func toBuilder() -> Google.Protobuf.StringValue.Builder {
      return Google.Protobuf.StringValue.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.StringValue) -> Google.Protobuf.StringValue.Builder {
      return Google.Protobuf.StringValue.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.StringValue"
    }
    override internal func className() -> String {
        return "Google.Protobuf.StringValue"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.StringValue.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.StringValue = Google.Protobuf.StringValue()
      internal func getMessage() -> Google.Protobuf.StringValue {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:String {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:String) -> Google.Protobuf.StringValue.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.StringValue.Builder{
           builderResult.hasValue = false
           builderResult.value = ""
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.StringValue.Builder {
        builderResult = Google.Protobuf.StringValue()
        return self
      }
      internal override func clone() -> Google.Protobuf.StringValue.Builder {
        return Google.Protobuf.StringValue.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.StringValue {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.StringValue {
        var returnMe:Google.Protobuf.StringValue = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.StringValue) -> Google.Protobuf.StringValue.Builder {
        if other == Google.Protobuf.StringValue() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.StringValue.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.StringValue.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 10 :
            value = input.readString()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

  final internal class BytesValue : GeneratedMessage, GeneratedMessageProtocol, Hashable {
    private(set) var hasValue:Bool = false
    private(set) var value:NSData = NSData()

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) {
      if hasValue {
        output.writeData(1, value:value)
      }
      unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasValue {
        serialize_size += value.computeDataSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseFromData(data:NSData) -> Google.Protobuf.BytesValue {
      return Google.Protobuf.BytesValue.builder().mergeFromData(data, extensionRegistry:Google.Protobuf.WrappersRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BytesValue {
      return Google.Protobuf.BytesValue.builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) -> Google.Protobuf.BytesValue {
      return Google.Protobuf.BytesValue.builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BytesValue {
      return Google.Protobuf.BytesValue.builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.BytesValue {
      return Google.Protobuf.BytesValue.builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BytesValue {
      return Google.Protobuf.BytesValue.builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func builder() -> Google.Protobuf.BytesValue.Builder {
      return Google.Protobuf.BytesValue.classBuilder() as! Google.Protobuf.BytesValue.Builder
    }
    internal func builder() -> Google.Protobuf.BytesValue.Builder {
      return classBuilder() as! Google.Protobuf.BytesValue.Builder
    }
    internal override class func classBuilder() -> MessageBuilder {
      return Google.Protobuf.BytesValue.Builder()
    }
    internal override func classBuilder() -> MessageBuilder {
      return Google.Protobuf.BytesValue.builder()
    }
    internal func toBuilder() -> Google.Protobuf.BytesValue.Builder {
      return Google.Protobuf.BytesValue.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Google.Protobuf.BytesValue) -> Google.Protobuf.BytesValue.Builder {
      return Google.Protobuf.BytesValue.builder().mergeFrom(prototype)
    }
    override internal func writeDescriptionTo(inout output:String, indent:String) {
      if hasValue {
        output += "\(indent) value: \(value) \n"
      }
      unknownFields.writeDescriptionTo(&output, indent:indent)
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasValue {
               hashCode = (hashCode &* 31) &+ value.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Google.Protobuf.BytesValue"
    }
    override internal func className() -> String {
        return "Google.Protobuf.BytesValue"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Google.Protobuf.BytesValue.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Google.Protobuf.BytesValue = Google.Protobuf.BytesValue()
      internal func getMessage() -> Google.Protobuf.BytesValue {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasValue:Bool {
           get {
                return builderResult.hasValue
           }
      }
      var value:NSData {
           get {
                return builderResult.value
           }
           set (value) {
               builderResult.hasValue = true
               builderResult.value = value
           }
      }
      func setValue(value:NSData) -> Google.Protobuf.BytesValue.Builder {
        self.value = value
        return self
      }
      internal func clearValue() -> Google.Protobuf.BytesValue.Builder{
           builderResult.hasValue = false
           builderResult.value = NSData()
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      internal override func clear() -> Google.Protobuf.BytesValue.Builder {
        builderResult = Google.Protobuf.BytesValue()
        return self
      }
      internal override func clone() -> Google.Protobuf.BytesValue.Builder {
        return Google.Protobuf.BytesValue.builderWithPrototype(builderResult)
      }
      internal override func build() -> Google.Protobuf.BytesValue {
           checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Google.Protobuf.BytesValue {
        var returnMe:Google.Protobuf.BytesValue = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Google.Protobuf.BytesValue) -> Google.Protobuf.BytesValue.Builder {
        if other == Google.Protobuf.BytesValue() {
         return self
        }
        if other.hasValue {
             value = other.value
        }
        mergeUnknownFields(other.unknownFields)
        return self
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream) -> Google.Protobuf.BytesValue.Builder {
           return mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      internal override func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) -> Google.Protobuf.BytesValue.Builder {
        var unknownFieldsBuilder:UnknownFieldSetBuilder = UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          var tag = input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = unknownFieldsBuilder.build()
            return self

          case 10 :
            value = input.readData()

          default:
            if (!parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag)) {
               unknownFields = unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
