// Generated by the Protocol Buffers 3.0 compiler.  DO NOT EDIT!
// Source file "foo.proto"
// Syntax "Proto2"

import Foundation
import ProtocolBuffers


internal struct Baz { }

internal func == (lhs: Baz.Foo, rhs: Baz.Foo) -> Bool {
  if (lhs === rhs) {
    return true
  }
  var fieldCheck:Bool = (lhs.hashValue == rhs.hashValue)
  fieldCheck = fieldCheck && (lhs.hasHello == rhs.hasHello) && (!lhs.hasHello || lhs.hello == rhs.hello)
  fieldCheck = (fieldCheck && (lhs.unknownFields == rhs.unknownFields))
  return fieldCheck
}

internal extension Baz {
  internal struct FooRoot {
    internal static var sharedInstance : FooRoot {
     struct Static {
         static let instance : FooRoot = FooRoot()
     }
     return Static.instance
    }
    internal var extensionRegistry:ExtensionRegistry

    init() {
      extensionRegistry = ExtensionRegistry()
      registerAllExtensions(extensionRegistry)
    }
    internal func registerAllExtensions(registry:ExtensionRegistry) {
    }
  }

  final internal class Foo : GeneratedMessage, GeneratedMessageProtocol {
    private(set) var hasHello:Bool = false
    private(set) var hello:String = ""

    required internal init() {
         super.init()
    }
    override internal func isInitialized() -> Bool {
     return true
    }
    override internal func writeToCodedOutputStream(output:CodedOutputStream) throws {
      if hasHello {
        try output.writeString(1, value:hello)
      }
      try unknownFields.writeToCodedOutputStream(output)
    }
    override internal func serializedSize() -> Int32 {
      var serialize_size:Int32 = memoizedSerializedSize
      if serialize_size != -1 {
       return serialize_size
      }

      serialize_size = 0
      if hasHello {
        serialize_size += hello.computeStringSize(1)
      }
      serialize_size += unknownFields.serializedSize()
      memoizedSerializedSize = serialize_size
      return serialize_size
    }
    internal class func parseArrayDelimitedFromInputStream(input:NSInputStream) throws -> Array<Baz.Foo> {
      var mergedArray = Array<Baz.Foo>()
      while let value = try parseFromDelimitedFromInputStream(input) {
        mergedArray += [value]
      }
      return mergedArray
    }
    internal class func parseFromDelimitedFromInputStream(input:NSInputStream) throws -> Baz.Foo? {
      return try Baz.Foo.Builder().mergeDelimitedFromInputStream(input)?.build()
    }
    internal class func parseFromData(data:NSData) throws -> Baz.Foo {
      return try Baz.Foo.Builder().mergeFromData(data, extensionRegistry:Baz.FooRoot.sharedInstance.extensionRegistry).build()
    }
    internal class func parseFromData(data:NSData, extensionRegistry:ExtensionRegistry) throws -> Baz.Foo {
      return try Baz.Foo.Builder().mergeFromData(data, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromInputStream(input:NSInputStream) throws -> Baz.Foo {
      return try Baz.Foo.Builder().mergeFromInputStream(input).build()
    }
    internal class func parseFromInputStream(input:NSInputStream, extensionRegistry:ExtensionRegistry) throws -> Baz.Foo {
      return try Baz.Foo.Builder().mergeFromInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream) throws -> Baz.Foo {
      return try Baz.Foo.Builder().mergeFromCodedInputStream(input).build()
    }
    internal class func parseFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Baz.Foo {
      return try Baz.Foo.Builder().mergeFromCodedInputStream(input, extensionRegistry:extensionRegistry).build()
    }
    internal class func getBuilder() -> Baz.Foo.Builder {
      return Baz.Foo.classBuilder() as! Baz.Foo.Builder
    }
    internal func getBuilder() -> Baz.Foo.Builder {
      return classBuilder() as! Baz.Foo.Builder
    }
    override internal class func classBuilder() -> MessageBuilder {
      return Baz.Foo.Builder()
    }
    override internal func classBuilder() -> MessageBuilder {
      return Baz.Foo.Builder()
    }
    internal func toBuilder() throws -> Baz.Foo.Builder {
      return try Baz.Foo.builderWithPrototype(self)
    }
    internal class func builderWithPrototype(prototype:Baz.Foo) throws -> Baz.Foo.Builder {
      return try Baz.Foo.Builder().mergeFrom(prototype)
    }
    override internal func encode() throws -> Dictionary<String,AnyObject> {
      guard isInitialized() else {
        throw ProtocolBuffersError.InvalidProtocolBuffer("Uninitialized Message")
      }

      var jsonMap:Dictionary<String,AnyObject> = Dictionary<String,AnyObject>()
      if hasHello {
        jsonMap["hello"] = hello
      }
      return jsonMap
    }
    override class internal func decode(jsonMap:Dictionary<String,AnyObject>) throws -> Baz.Foo {
      return try Baz.Foo.Builder.decodeToBuilder(jsonMap).build()
    }
    override class internal func fromJSON(data:NSData) throws -> Baz.Foo {
      return try Baz.Foo.Builder.fromJSONToBuilder(data).build()
    }
    override internal func getDescription(indent:String) throws -> String {
      var output = ""
      if hasHello {
        output += "\(indent) hello: \(hello) \n"
      }
      output += unknownFields.getDescription(indent)
      return output
    }
    override internal var hashValue:Int {
        get {
            var hashCode:Int = 7
            if hasHello {
               hashCode = (hashCode &* 31) &+ hello.hashValue
            }
            hashCode = (hashCode &* 31) &+  unknownFields.hashValue
            return hashCode
        }
    }


    //Meta information declaration start

    override internal class func className() -> String {
        return "Baz.Foo"
    }
    override internal func className() -> String {
        return "Baz.Foo"
    }
    override internal func classMetaType() -> GeneratedMessage.Type {
        return Baz.Foo.self
    }
    //Meta information declaration end

    final internal class Builder : GeneratedMessageBuilder {
      private var builderResult:Baz.Foo = Baz.Foo()
      internal func getMessage() -> Baz.Foo {
          return builderResult
      }

      required override internal init () {
         super.init()
      }
      var hasHello:Bool {
           get {
                return builderResult.hasHello
           }
      }
      var hello:String {
           get {
                return builderResult.hello
           }
           set (value) {
               builderResult.hasHello = true
               builderResult.hello = value
           }
      }
      func setHello(value:String) -> Baz.Foo.Builder {
        self.hello = value
        return self
      }
      internal func clearHello() -> Baz.Foo.Builder{
           builderResult.hasHello = false
           builderResult.hello = ""
           return self
      }
      override internal var internalGetResult:GeneratedMessage {
           get {
              return builderResult
           }
      }
      override internal func clear() -> Baz.Foo.Builder {
        builderResult = Baz.Foo()
        return self
      }
      override internal func clone() throws -> Baz.Foo.Builder {
        return try Baz.Foo.builderWithPrototype(builderResult)
      }
      override internal func build() throws -> Baz.Foo {
           try checkInitialized()
           return buildPartial()
      }
      internal func buildPartial() -> Baz.Foo {
        let returnMe:Baz.Foo = builderResult
        return returnMe
      }
      internal func mergeFrom(other:Baz.Foo) throws -> Baz.Foo.Builder {
        if other == Baz.Foo() {
         return self
        }
        if other.hasHello {
             hello = other.hello
        }
        try mergeUnknownFields(other.unknownFields)
        return self
      }
      override internal func mergeFromCodedInputStream(input:CodedInputStream) throws -> Baz.Foo.Builder {
           return try mergeFromCodedInputStream(input, extensionRegistry:ExtensionRegistry())
      }
      override internal func mergeFromCodedInputStream(input:CodedInputStream, extensionRegistry:ExtensionRegistry) throws -> Baz.Foo.Builder {
        let unknownFieldsBuilder:UnknownFieldSet.Builder = try UnknownFieldSet.builderWithUnknownFields(self.unknownFields)
        while (true) {
          let tag = try input.readTag()
          switch tag {
          case 0: 
            self.unknownFields = try unknownFieldsBuilder.build()
            return self

          case 10 :
            hello = try input.readString()

          default:
            if (!(try parseUnknownField(input,unknownFields:unknownFieldsBuilder, extensionRegistry:extensionRegistry, tag:tag))) {
               unknownFields = try unknownFieldsBuilder.build()
               return self
            }
          }
        }
      }
      override class internal func decodeToBuilder(jsonMap:Dictionary<String,AnyObject>) throws -> Baz.Foo.Builder {
        let resultDecodedBuilder = Baz.Foo.Builder()
        if let jsonValueHello = jsonMap["hello"] as? String {
          resultDecodedBuilder.hello = jsonValueHello
        }
        return resultDecodedBuilder
      }
      override class internal func fromJSONToBuilder(data:NSData) throws -> Baz.Foo.Builder {
        let jsonData = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions(rawValue: 0))
        guard let jsDataCast = jsonData as? Dictionary<String,AnyObject> else {
          throw ProtocolBuffersError.InvalidProtocolBuffer("Invalid JSON data")
        }
        return try Baz.Foo.Builder.decodeToBuilder(jsDataCast)
      }
    }

  }

}

// @@protoc_insertion_point(global_scope)
