// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Performance.proto

public final class Performance {
  private Performance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IceCreamConeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IceCreamCone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 scoops = 1;</code>
     *
     * <pre>
     * enum Flavor {
     *   CHOCOLATE = 1;
     *   VANILLA = 2;
     * }
     * </pre>
     */
    int getScoops();

    /**
     * <code>map&lt;int32, .ProtoPoint&gt; mapper = 3;</code>
     *
     * <pre>
     * Flavor flavor = 2;
     * </pre>
     */
    java.util.Map<java.lang.Integer, Performance.ProtoPoint>
    getMapper();
  }
  /**
   * Protobuf type {@code IceCreamCone}
   */
  public  static final class IceCreamCone extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:IceCreamCone)
      IceCreamConeOrBuilder {
    // Use IceCreamCone.newBuilder() to construct.
    private IceCreamCone(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private IceCreamCone() {
      scoops_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private IceCreamCone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              scoops_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                mapper_ = com.google.protobuf.MapField.newMapField(
                    mapperDefaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, Performance.ProtoPoint>
              mapper = input.readMessage(
                  mapperDefaultEntry.getParserForType(), extensionRegistry);
              mapper_.getMutableMap().put(mapper.getKey(), mapper.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Performance.internal_static_IceCreamCone_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return mapper_;
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Performance.internal_static_IceCreamCone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Performance.IceCreamCone.class, Performance.IceCreamCone.Builder.class);
    }

    public static final com.google.protobuf.Parser<IceCreamCone> PARSER =
        new com.google.protobuf.AbstractParser<IceCreamCone>() {
      public IceCreamCone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IceCreamCone(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<IceCreamCone> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SCOOPS_FIELD_NUMBER = 1;
    private int scoops_;
    /**
     * <code>optional int32 scoops = 1;</code>
     *
     * <pre>
     * enum Flavor {
     *   CHOCOLATE = 1;
     *   VANILLA = 2;
     * }
     * </pre>
     */
    public int getScoops() {
      return scoops_;
    }

    public static final int MAPPER_FIELD_NUMBER = 3;
    private static final com.google.protobuf.MapEntry<
        java.lang.Integer, Performance.ProtoPoint> mapperDefaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, Performance.ProtoPoint>newDefaultInstance(
                Performance.internal_static_IceCreamCone_MapperEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                Performance.ProtoPoint.getDefaultInstance());
    private com.google.protobuf.MapField<
        java.lang.Integer, Performance.ProtoPoint> mapper_ =
            com.google.protobuf.MapField.emptyMapField(
                mapperDefaultEntry);

    /**
     * <code>map&lt;int32, .ProtoPoint&gt; mapper = 3;</code>
     *
     * <pre>
     * Flavor flavor = 2;
     * </pre>
     */

    public java.util.Map<java.lang.Integer, Performance.ProtoPoint> getMapper() {
      return mapper_.getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (scoops_ != 0) {
        output.writeInt32(1, scoops_);
      }
      for (java.util.Map.Entry<java.lang.Integer, Performance.ProtoPoint> entry
           : mapper_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, Performance.ProtoPoint>
        mapper = mapperDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, mapper);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (scoops_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, scoops_);
      }
      for (java.util.Map.Entry<java.lang.Integer, Performance.ProtoPoint> entry
           : mapper_.getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, Performance.ProtoPoint>
        mapper = mapperDefaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, mapper);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Performance.IceCreamCone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Performance.IceCreamCone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Performance.IceCreamCone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Performance.IceCreamCone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Performance.IceCreamCone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Performance.IceCreamCone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Performance.IceCreamCone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Performance.IceCreamCone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Performance.IceCreamCone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Performance.IceCreamCone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Performance.IceCreamCone prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IceCreamCone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IceCreamCone)
        Performance.IceCreamConeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Performance.internal_static_IceCreamCone_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return mapper_;
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Performance.internal_static_IceCreamCone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Performance.IceCreamCone.class, Performance.IceCreamCone.Builder.class);
      }

      // Construct using Performance.IceCreamCone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        scoops_ = 0;

        mapper_.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Performance.internal_static_IceCreamCone_descriptor;
      }

      public Performance.IceCreamCone getDefaultInstanceForType() {
        return Performance.IceCreamCone.getDefaultInstance();
      }

      public Performance.IceCreamCone build() {
        Performance.IceCreamCone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Performance.IceCreamCone buildPartial() {
        Performance.IceCreamCone result = new Performance.IceCreamCone(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.scoops_ = scoops_;
        result.mapper_ = mapper_.copy();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Performance.IceCreamCone) {
          return mergeFrom((Performance.IceCreamCone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Performance.IceCreamCone other) {
        if (other == Performance.IceCreamCone.getDefaultInstance()) return this;
        if (other.getScoops() != 0) {
          setScoops(other.getScoops());
        }
        mapper_.mergeFrom(other.mapper_);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Performance.IceCreamCone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Performance.IceCreamCone) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int scoops_ ;
      /**
       * <code>optional int32 scoops = 1;</code>
       *
       * <pre>
       * enum Flavor {
       *   CHOCOLATE = 1;
       *   VANILLA = 2;
       * }
       * </pre>
       */
      public int getScoops() {
        return scoops_;
      }
      /**
       * <code>optional int32 scoops = 1;</code>
       *
       * <pre>
       * enum Flavor {
       *   CHOCOLATE = 1;
       *   VANILLA = 2;
       * }
       * </pre>
       */
      public Builder setScoops(int value) {
        
        scoops_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 scoops = 1;</code>
       *
       * <pre>
       * enum Flavor {
       *   CHOCOLATE = 1;
       *   VANILLA = 2;
       * }
       * </pre>
       */
      public Builder clearScoops() {
        
        scoops_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, Performance.ProtoPoint> mapper_ =
              com.google.protobuf.MapField.newMapField(
                  mapperDefaultEntry);

      /**
       * <code>map&lt;int32, .ProtoPoint&gt; mapper = 3;</code>
       *
       * <pre>
       * Flavor flavor = 2;
       * </pre>
       */
      public java.util.Map<java.lang.Integer, Performance.ProtoPoint> getMapper() {
        return mapper_.getMap();
      }
      /**
       * <code>map&lt;int32, .ProtoPoint&gt; mapper = 3;</code>
       *
       * <pre>
       * Flavor flavor = 2;
       * </pre>
       */
      public java.util.Map<java.lang.Integer, Performance.ProtoPoint>
      getMutableMapper() {
        onChanged();
        return mapper_.getMutableMap();
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:IceCreamCone)
    }

    // @@protoc_insertion_point(class_scope:IceCreamCone)
    private static final Performance.IceCreamCone defaultInstance;static {
      defaultInstance = new Performance.IceCreamCone();
    }

    public static Performance.IceCreamCone getDefaultInstance() {
      return defaultInstance;
    }

    public Performance.IceCreamCone getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  public interface ProtoPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoPoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float latitude = 1;</code>
     */
    float getLatitude();

    /**
     * <code>optional float longitude = 2;</code>
     */
    float getLongitude();
  }
  /**
   * Protobuf type {@code ProtoPoint}
   */
  public  static final class ProtoPoint extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProtoPoint)
      ProtoPointOrBuilder {
    // Use ProtoPoint.newBuilder() to construct.
    private ProtoPoint(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private ProtoPoint() {
      latitude_ = 0F;
      longitude_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProtoPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              latitude_ = input.readFloat();
              break;
            }
            case 21: {

              longitude_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Performance.internal_static_ProtoPoint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Performance.internal_static_ProtoPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Performance.ProtoPoint.class, Performance.ProtoPoint.Builder.class);
    }

    public static final com.google.protobuf.Parser<ProtoPoint> PARSER =
        new com.google.protobuf.AbstractParser<ProtoPoint>() {
      public ProtoPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPoint(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoPoint> getParserForType() {
      return PARSER;
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private float latitude_;
    /**
     * <code>optional float latitude = 1;</code>
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private float longitude_;
    /**
     * <code>optional float longitude = 2;</code>
     */
    public float getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (latitude_ != 0F) {
        output.writeFloat(1, latitude_);
      }
      if (longitude_ != 0F) {
        output.writeFloat(2, longitude_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, latitude_);
      }
      if (longitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, longitude_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Performance.ProtoPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Performance.ProtoPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Performance.ProtoPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Performance.ProtoPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Performance.ProtoPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Performance.ProtoPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Performance.ProtoPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Performance.ProtoPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Performance.ProtoPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Performance.ProtoPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Performance.ProtoPoint prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoPoint)
        Performance.ProtoPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Performance.internal_static_ProtoPoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Performance.internal_static_ProtoPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Performance.ProtoPoint.class, Performance.ProtoPoint.Builder.class);
      }

      // Construct using Performance.ProtoPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0F;

        longitude_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Performance.internal_static_ProtoPoint_descriptor;
      }

      public Performance.ProtoPoint getDefaultInstanceForType() {
        return Performance.ProtoPoint.getDefaultInstance();
      }

      public Performance.ProtoPoint build() {
        Performance.ProtoPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Performance.ProtoPoint buildPartial() {
        Performance.ProtoPoint result = new Performance.ProtoPoint(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Performance.ProtoPoint) {
          return mergeFrom((Performance.ProtoPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Performance.ProtoPoint other) {
        if (other == Performance.ProtoPoint.getDefaultInstance()) return this;
        if (other.getLatitude() != 0F) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0F) {
          setLongitude(other.getLongitude());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Performance.ProtoPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Performance.ProtoPoint) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float latitude_ ;
      /**
       * <code>optional float latitude = 1;</code>
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <code>optional float latitude = 1;</code>
       */
      public Builder setLatitude(float value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float latitude = 1;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>optional float longitude = 2;</code>
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>optional float longitude = 2;</code>
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float longitude = 2;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ProtoPoint)
    }

    // @@protoc_insertion_point(class_scope:ProtoPoint)
    private static final Performance.ProtoPoint defaultInstance;static {
      defaultInstance = new Performance.ProtoPoint();
    }

    public static Performance.ProtoPoint getDefaultInstance() {
      return defaultInstance;
    }

    public Performance.ProtoPoint getDefaultInstanceForType() {
      return defaultInstance;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IceCreamCone_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IceCreamCone_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IceCreamCone_MapperEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IceCreamCone_MapperEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoPoint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoPoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Performance.proto\"\205\001\n\014IceCreamCone\022\016\n\006" +
      "scoops\030\001 \001(\005\022)\n\006mapper\030\003 \003(\0132\031.IceCreamC" +
      "one.MapperEntry\032:\n\013MapperEntry\022\013\n\003key\030\001 " +
      "\001(\005\022\032\n\005value\030\002 \001(\0132\013.ProtoPoint:\0028\001\"1\n\nP" +
      "rotoPoint\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlongitude" +
      "\030\002 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_IceCreamCone_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IceCreamCone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IceCreamCone_descriptor,
        new java.lang.String[] { "Scoops", "Mapper", });
    internal_static_IceCreamCone_MapperEntry_descriptor =
      internal_static_IceCreamCone_descriptor.getNestedTypes().get(0);
    internal_static_IceCreamCone_MapperEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_IceCreamCone_MapperEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_ProtoPoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProtoPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProtoPoint_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
